config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end

  resources :docs

  authenticated :user do
  	root "docs#index", as: "authenticated_root"
  end
  
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :docs

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
  	@docs = Doc.where(user_id: current_user)
  end

  def new
  	@doc = current_user.docs.build
  end

  def create
  	@doc = current_user.docs.build(doc_params)
  	if @doc.save
  		redirect_to @doc
  	else
  		render :new
  	end
  end

  def show
  	@doc = Doc.find(params[:id])
  end

  def edit
  	@doc = Doc.find(params[:id])
  end

  def update
  	@doc = Doc.find(params[:id])

  	if @doc.update(doc_params)
  		redirect_to @doc
  		else
  			render :edit
  	end
  end

  def destroy
  	@doc = Doc.find(params[:id])

  	@doc.destroy
  	redirect_to :action => :index
  end

  private

  def doc_params
  	params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<div class="flex-row d-flex justify-content-center">
	<div class="col-md-8">
	<%= form_for @doc do |f| %>
	<div class="form-group">
		<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
	</div>	
	<div class="form-group">
	<%= f.label :content %>
	<%= f.text_area :content, class: 'form-control' %>
	</div>

	<%= f.submit "Create Document", class: 'btn btn-outline-primary' %>
	<%= link_to "Back", docs_path, class: 'btn btn-outline-secondary' %>
<% end %>
	</div>

</div>

app/views/docs/edit.html.erb
<%= render "form" %>

app/views/docs/index.html.erb
<div class="container">
	<div class="row">

	<% @docs.each do |doc| %>

	<div class="col-md-4">
		<div class="card mt-3">
			<div class="card-body">

				<h3><%= link_to doc.title, doc_path(doc.id) %></h3>
	            <p><%= time_ago_in_words(doc.created_at) %></p>
	            <p><%= truncate(doc.content, length:50) %></p>
	
			</div>
		</div>
	</div>

	
<% end %>

	</div>
</div>

app/views/docs/new.html.erb
<%= render "form" %>

app/views/docs/show.html.erb
<div class="container-fluid">

<h3><%= simple_format(@doc.title) %></h3>

<p><%= @doc.content %></p>

<table>
	<tbody>
		<td><%= link_to "Edit", edit_doc_path(@doc.id), class: 'btn btn-primary' %></td>
		<td><%= button_to "Delete", doc_path(@doc.id), method: :delete, class: 'btn btn-danger' %>
</td>
		<td><%= link_to "Back", docs_path, class: 'btn btn-secondary' %></td>
	</tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">FileCabinet</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Create Doc", new_doc_path %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
      <% else%>
      <li><%= link_to "login", new_user_session_path %></li>
       <% end %>
      </ul>
     
  </div>
</nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center">
	
		<h1>FileCabinet</h1>

		<p>Your life's work. Organized, always</p>
		<%= link_to "Enter", new_user_registration_path, class: 'btn btn-dark' %>

</div>